### ISSUE TITLE
reading all months using for loop

### ISSUE THREAD

**Issue by lhamon31** [lhamon31/butterfliesNC#4]
I'm modifying the papilio-glaucus script to read in all mean temp values for all years for all species. Not sure how to approach initial for loop part (lines 53-62 of script) so that it will read in the different 8 months I want for each species. perhaps write different functions for all desired month possibilities to be included in the loop (ie, one for single-digit months in the same year, one for single-digit months in previous year and one for double-digit months in previous year)?

**Comment by ahhurlbert** [comment]
I modified the code, added a species loop, and changed how we specify the filenames to read in so that they are species-specific.

The output is now also in a different format, a 4 col dataframe with fields for county, species, year, and mean temperature.

Might still be a few bugs in it, but see if you can get it to work and if you understand what the code is doing (or trying to do!).

**Comment by lhamon31** [comment]
Many thanks! That makes more sense. I'll try to get it to run and report back. Thanks again!

**Comment by lhamon31** [comment]
I'm not sure I understand the output- I ran the data for 2010:2014 and 'output' returns a list of 325 mean temperature values without labels. This is the correct amount of values since I want a mean temp value for each year for each species (65 spp X 5 years). Should I assume that the 'output' is listed in order of species and year and use binding and merging methods to restructure it so it reads how I want? I'm not sure if it's noteworthy that the preceding 'tempoutput' object returns labelled county, species, year, and temp values, but for only only species (Wallengrenia otho) and one year (2014).

**Comment by ahhurlbert** [comment]
Try it now. There was an error in the rbind command.

**Comment by lhamon31** [comment]
It works! I'll work on merging it with the julian data and plotting. Thanks again!
