### ISSUE TITLE
generating a slope data frame

### ISSUE THREAD

**Issue by lhamon31** [lhamon31/butterfliesNC#5]
I wanted to create a dataframe of slopes, r-squared, and p-values for each species for each of my 3 counties of interest. When I run lines 71-onwards in order to generate a dataframe of regression slopes for each species for county, no values appear in the output. There may be an issue in the way I've formatted lines 71-80

**Comment by ahhurlbert** [comment]
First, double-check that there are records in buncombe.dat using `dim(buncombe.dat`.
Then try setting `s = species[1]` and then run the code inside the loop (lines 72-78). What does `df` look like? Did the linear model run? Did `tempoutput` get created, and does it have the regression output?

Stepping through the innards of a loop line by line can help identify where the problem arose.

**Comment by lhamon31** [comment]
Thank you! It appears that it was having issues with NA rows and with species that only had one data point. It ran when I excluded these rows.
